name: pydevicetree-tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          make virtualenv
      - name: Check types with mypy
        run:
          make test-types
      - name: Lint with pylint
        run:
          make test-lint
      - name: Run unit tests
        run:
          make test-unit
      - name: Run integration tests
        run:
          make test-integration

